CI/CD: Fix deploy consistent with pyproject.toml
pymoca/pymoca pull request #342
Opened 2024-12-27 18:06 UTC by kentrutan

Change from the old setup.py-based build to something consistent with current Python packaging standards (though the instructions are poorly documented). I guess we have not done a deploy since the change to pyproject.toml, so this is the first time we are seeing the issue.

2024-12-27 21:58 UTC, kentrutan commented
Getting pymoca version 0.0.0. Thought it was versioneer needing Python <= 3.11, but that's not it. Perhaps a setuptools with the new build system is clashing? TBD

2024-12-31 17:39 UTC, kentrutan commented
The last push has a solution, but I'm not totally confident that it will work in future versions of setuptools and/or versioneer (details in 173a327 message). Maybe the long-term solution is to look for ways to get #303 to work in the context of #287.

setuptools_scm is currently bit ahead versioneer in the latest release (May 2024 vs July 2023). They are both currently testing only up to Python 3.12, so our support of Python 3.13 is a bit ahead of them, but seems to work OK. Neither test against macOS ☹️.

2024-12-31 23:54 UTC, kentrutan commented
Last two commits fix warnings I saw in the build where files from MANIFEST.in were not included in the distribution. Thought I would go ahead and fix for the next release.

2025-01-01 00:23 UTC, kentrutan commented
We now have a proper project description on PyPI from the README. There are a couple loose ends related to that that I want to fix for the 0.11.0 release.

- Fix the description in `pyproject.toml` to be consistent with the README (already pushed the commit to fix).
- Fix the broken pymoca image on PyPI that is OK on GitHub README. Yet to be fixed.

2025-01-01 03:12 UTC, kentrutan commented
OK I think we are ready for an official 0.11.0 release with all README images and links working on TestPyPI (and hopefully PyPI after the CI/deploy with the 0.11.0.dev6 release completes).

2025-01-01 11:43 UTC, jackvreeken commented
Nice cleanups! And for sure, the versioneer + setuptools_scm could do with a revisit. The big thing there is cache invalidation with local development by detecting "dirty" iirc.

2025-01-06 19:41 UTC, kentrutan commented
Hello @jackvreeken. Is reviewing this on your radar? No hurry, just wondering.

2025-01-07 12:23 UTC, jackvreeken requested changes
Just some wrapping in the commit message(s). Otherwise looks absolutely great to me!

2025-01-07 12:23 UTC, jackvreeken commented on .github/workflows/ci.yml
>      - run: |
(related to the commit message of the first commit) The paragraph starting with `Adding `setup.py` back in could be a fall-back solution` is not wrapped in the commit message.

2025-01-07 12:26 UTC, jackvreeken commented
On the topic of pyproject.toml, and what tool to use to build, I've recently been using `uv` a lot at <dayjob>. It's by the makers of Ruff, and it works really smoothly so far. Somewhere down the line I'll give setuptools_scm a go again, maybe now it'll work with your `tool.setuptools.dynamic` section change (and/or `uv` making things easy to install/upkeep)

2025-01-07 16:03 UTC, jackvreeken commented
LGTM!

2025-01-07 17:16 UTC, merged